"""VNFLocation table, add NSD,Slice to Experiment

Revision ID: 01a9a57a22c5
Revises: 3412f1db797d
Create Date: 2019-05-20 15:41:07.447160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a9a57a22c5'
down_revision = '3412f1db797d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vnf_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('VNF_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['VNF_id'], ['VNF.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('experiment', sa.Column('NSD', sa.String(length=256), nullable=True))
    op.add_column('experiment', sa.Column('slice', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('vnf_location')
	with op.batch_alter_table("experiment") as batch:
		batch.drop_column('slice')
		batch.drop_column('NSD')
    # ### end Alembic commands ###
