"""VNF table

Revision ID: 118829a7240c
Revises: e88a98d29968
Create Date: 2019-05-15 10:08:23.668540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118829a7240c'
down_revision = 'e88a98d29968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VNF',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('VNFD', sa.String(length=256), nullable=True),
    sa.Column('NDS', sa.String(length=256), nullable=True),
    sa.Column('NST', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VNF')
    # ### end Alembic commands ###
