"""organization column - User table

Revision ID: 2e897fa58901
Revises: 6b62cdd3fc52
Create Date: 2019-03-19 12:01:52.601853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e897fa58901'
down_revision = '6b62cdd3fc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization')
    # ### end Alembic commands ###
