"""alter VNF table

Revision ID: 3412f1db797d
Revises: 118829a7240c
Create Date: 2019-05-20 15:14:54.042726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3412f1db797d'
down_revision = '118829a7240c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("VNF") as batch:
		batch.drop_column('NDS')
		batch.drop_column('NST')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VNF', sa.Column('NST', sa.VARCHAR(length=256), nullable=True))
    op.add_column('VNF', sa.Column('NDS', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
