"""Add NS relation

Revision ID: b8410a700609
Revises: 8f5ef6e08318
Create Date: 2019-09-17 15:11:54.218111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8410a700609'
down_revision = '8f5ef6e08318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments_ns',
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('ns_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['ns_id'], ['NS.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments_ns')
    # ### end Alembic commands ###
