"""remove vnflocations

Revision ID: f50d434a1dd2
Revises: 5a4d3cdf3c1c
Create Date: 2019-09-16 14:16:08.671325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50d434a1dd2'
down_revision = '5a4d3cdf3c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vnf_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vnf_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=32), nullable=True),
    sa.Column('VNF_id', sa.INTEGER(), nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['VNF_id'], ['VNF.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
